export const ROUTES = {
  display: '/cas/tv/affichage',
  flow: '/cas/tv/flow',
  flowAdmin: '/cas/tv/flow-admin',
  layouts: '/cas/tv/layouts',
  participants: '/cas/tv/participants',
  admin: '/cas/tv/admin',
  results: '/cas/tv/resultats',
  runs: '/cas/tv/runs',
  archives: '/cas/tv/archives',
  chrono: '/cas/chrono',
};

export const LEGACY_ROUTE_REDIRECTS = [
  { from: '/', to: ROUTES.display },
  { from: '/cas', to: ROUTES.display },
  { from: '/cas/tv', to: ROUTES.display },
  { from: '/config', to: ROUTES.flow },
  { from: '/streams-admin', to: ROUTES.flowAdmin },
  { from: '/participants', to: ROUTES.participants },
  { from: '/layouts', to: ROUTES.layouts },
  { from: '/admin', to: ROUTES.admin },
  { from: '/results-view', to: ROUTES.results },
  { from: '/results-admin', to: ROUTES.results },
  { from: '/results-runs', to: ROUTES.runs },
  { from: '/results-archives', to: ROUTES.archives },
  { from: '/results', to: ROUTES.chrono },
  { from: '/cas/affichage', to: ROUTES.display },
  { from: '/cas/flow', to: ROUTES.flow },
  { from: '/cas/flow-admin', to: ROUTES.flowAdmin },
  { from: '/cas/layouts', to: ROUTES.layouts },
  { from: '/cas/participants', to: ROUTES.participants },
  { from: '/cas/admin', to: ROUTES.admin },
  { from: '/cas/resultats', to: ROUTES.results },
  { from: '/cas/runs', to: ROUTES.runs },
  { from: '/cas/archives', to: ROUTES.archives },
  { from: '/cav/affichage', to: ROUTES.display },
  { from: '/cav/flow', to: ROUTES.flow },
  { from: '/cav/flow-admin', to: ROUTES.flowAdmin },
  { from: '/cav/layouts', to: ROUTES.layouts },
  { from: '/cav/participants', to: ROUTES.participants },
  { from: '/cav/admin', to: ROUTES.admin },
  { from: '/cav/resultats', to: ROUTES.results },
  { from: '/cav/runs', to: ROUTES.runs },
  { from: '/cav/archives', to: ROUTES.archives },
  { from: '/cav/chrono', to: ROUTES.chrono },
];
